(cl:defpackage urdf_tutorial-srv
  (:use )
  (:export
   "CHANGECONTROLLEDJOINTS"
   "<CHANGECONTROLLEDJOINTS-REQUEST>"
   "CHANGECONTROLLEDJOINTS-REQUEST"
   "<CHANGECONTROLLEDJOINTS-RESPONSE>"
   "CHANGECONTROLLEDJOINTS-RESPONSE"
   "CHANGESCALE"
   "<CHANGESCALE-REQUEST>"
   "CHANGESCALE-REQUEST"
   "<CHANGESCALE-RESPONSE>"
   "CHANGESCALE-RESPONSE"
  ))

