// Generated by gencpp from file message_tests/ChangerateResponse.msg
// DO NOT EDIT!


#ifndef MESSAGE_TESTS_MESSAGE_CHANGERATERESPONSE_H
#define MESSAGE_TESTS_MESSAGE_CHANGERATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace message_tests
{
template <class ContainerAllocator>
struct ChangerateResponse_
{
  typedef ChangerateResponse_<ContainerAllocator> Type;

  ChangerateResponse_()
    : ret(false)  {
    }
  ChangerateResponse_(const ContainerAllocator& _alloc)
    : ret(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ret_type;
  _ret_type ret;





  typedef boost::shared_ptr< ::message_tests::ChangerateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::message_tests::ChangerateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ChangerateResponse_

typedef ::message_tests::ChangerateResponse_<std::allocator<void> > ChangerateResponse;

typedef boost::shared_ptr< ::message_tests::ChangerateResponse > ChangerateResponsePtr;
typedef boost::shared_ptr< ::message_tests::ChangerateResponse const> ChangerateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::message_tests::ChangerateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::message_tests::ChangerateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::message_tests::ChangerateResponse_<ContainerAllocator1> & lhs, const ::message_tests::ChangerateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ret == rhs.ret;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::message_tests::ChangerateResponse_<ContainerAllocator1> & lhs, const ::message_tests::ChangerateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace message_tests

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::message_tests::ChangerateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message_tests::ChangerateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message_tests::ChangerateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message_tests::ChangerateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_tests::ChangerateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_tests::ChangerateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::message_tests::ChangerateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2cc9e9d8c464550830df49c160979ad";
  }

  static const char* value(const ::message_tests::ChangerateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2cc9e9d8c464550ULL;
  static const uint64_t static_value2 = 0x830df49c160979adULL;
};

template<class ContainerAllocator>
struct DataType< ::message_tests::ChangerateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "message_tests/ChangerateResponse";
  }

  static const char* value(const ::message_tests::ChangerateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::message_tests::ChangerateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ret\n"
;
  }

  static const char* value(const ::message_tests::ChangerateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::message_tests::ChangerateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangerateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::message_tests::ChangerateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::message_tests::ChangerateResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGE_TESTS_MESSAGE_CHANGERATERESPONSE_H
