// Generated by gencpp from file message_tests/ChangespeedRequest.msg
// DO NOT EDIT!


#ifndef MESSAGE_TESTS_MESSAGE_CHANGESPEEDREQUEST_H
#define MESSAGE_TESTS_MESSAGE_CHANGESPEEDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace message_tests
{
template <class ContainerAllocator>
struct ChangespeedRequest_
{
  typedef ChangespeedRequest_<ContainerAllocator> Type;

  ChangespeedRequest_()
    : speed(0.0)  {
    }
  ChangespeedRequest_(const ContainerAllocator& _alloc)
    : speed(0.0)  {
  (void)_alloc;
    }



   typedef double _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::message_tests::ChangespeedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::message_tests::ChangespeedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ChangespeedRequest_

typedef ::message_tests::ChangespeedRequest_<std::allocator<void> > ChangespeedRequest;

typedef boost::shared_ptr< ::message_tests::ChangespeedRequest > ChangespeedRequestPtr;
typedef boost::shared_ptr< ::message_tests::ChangespeedRequest const> ChangespeedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::message_tests::ChangespeedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::message_tests::ChangespeedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::message_tests::ChangespeedRequest_<ContainerAllocator1> & lhs, const ::message_tests::ChangespeedRequest_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::message_tests::ChangespeedRequest_<ContainerAllocator1> & lhs, const ::message_tests::ChangespeedRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace message_tests

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::message_tests::ChangespeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message_tests::ChangespeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message_tests::ChangespeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message_tests::ChangespeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_tests::ChangespeedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_tests::ChangespeedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::message_tests::ChangespeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4641bb0523a3557209606d9bd91ce33a";
  }

  static const char* value(const ::message_tests::ChangespeedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4641bb0523a35572ULL;
  static const uint64_t static_value2 = 0x09606d9bd91ce33aULL;
};

template<class ContainerAllocator>
struct DataType< ::message_tests::ChangespeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "message_tests/ChangespeedRequest";
  }

  static const char* value(const ::message_tests::ChangespeedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::message_tests::ChangespeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 speed\n"
;
  }

  static const char* value(const ::message_tests::ChangespeedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::message_tests::ChangespeedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangespeedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::message_tests::ChangespeedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::message_tests::ChangespeedRequest_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGE_TESTS_MESSAGE_CHANGESPEEDREQUEST_H
