// Generated by gencpp from file urdf_tutorial/changescale.msg
// DO NOT EDIT!


#ifndef URDF_TUTORIAL_MESSAGE_CHANGESCALE_H
#define URDF_TUTORIAL_MESSAGE_CHANGESCALE_H

#include <ros/service_traits.h>


#include <urdf_tutorial/changescaleRequest.h>
#include <urdf_tutorial/changescaleResponse.h>


namespace urdf_tutorial
{

struct changescale
{

typedef changescaleRequest Request;
typedef changescaleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct changescale
} // namespace urdf_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::urdf_tutorial::changescale > {
  static const char* value()
  {
    return "bc08dbcb40b2ba4b05703f0913420f07";
  }

  static const char* value(const ::urdf_tutorial::changescale&) { return value(); }
};

template<>
struct DataType< ::urdf_tutorial::changescale > {
  static const char* value()
  {
    return "urdf_tutorial/changescale";
  }

  static const char* value(const ::urdf_tutorial::changescale&) { return value(); }
};


// service_traits::MD5Sum< ::urdf_tutorial::changescaleRequest> should match
// service_traits::MD5Sum< ::urdf_tutorial::changescale >
template<>
struct MD5Sum< ::urdf_tutorial::changescaleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::urdf_tutorial::changescale >::value();
  }
  static const char* value(const ::urdf_tutorial::changescaleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::urdf_tutorial::changescaleRequest> should match
// service_traits::DataType< ::urdf_tutorial::changescale >
template<>
struct DataType< ::urdf_tutorial::changescaleRequest>
{
  static const char* value()
  {
    return DataType< ::urdf_tutorial::changescale >::value();
  }
  static const char* value(const ::urdf_tutorial::changescaleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::urdf_tutorial::changescaleResponse> should match
// service_traits::MD5Sum< ::urdf_tutorial::changescale >
template<>
struct MD5Sum< ::urdf_tutorial::changescaleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::urdf_tutorial::changescale >::value();
  }
  static const char* value(const ::urdf_tutorial::changescaleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::urdf_tutorial::changescaleResponse> should match
// service_traits::DataType< ::urdf_tutorial::changescale >
template<>
struct DataType< ::urdf_tutorial::changescaleResponse>
{
  static const char* value()
  {
    return DataType< ::urdf_tutorial::changescale >::value();
  }
  static const char* value(const ::urdf_tutorial::changescaleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // URDF_TUTORIAL_MESSAGE_CHANGESCALE_H
