// Generated by gencpp from file urdf_tutorial/changecontrolledjointsResponse.msg
// DO NOT EDIT!


#ifndef URDF_TUTORIAL_MESSAGE_CHANGECONTROLLEDJOINTSRESPONSE_H
#define URDF_TUTORIAL_MESSAGE_CHANGECONTROLLEDJOINTSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace urdf_tutorial
{
template <class ContainerAllocator>
struct changecontrolledjointsResponse_
{
  typedef changecontrolledjointsResponse_<ContainerAllocator> Type;

  changecontrolledjointsResponse_()
    {
    }
  changecontrolledjointsResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct changecontrolledjointsResponse_

typedef ::urdf_tutorial::changecontrolledjointsResponse_<std::allocator<void> > changecontrolledjointsResponse;

typedef boost::shared_ptr< ::urdf_tutorial::changecontrolledjointsResponse > changecontrolledjointsResponsePtr;
typedef boost::shared_ptr< ::urdf_tutorial::changecontrolledjointsResponse const> changecontrolledjointsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace urdf_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "urdf_tutorial/changecontrolledjointsResponse";
  }

  static const char* value(const ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct changecontrolledjointsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::urdf_tutorial::changecontrolledjointsResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // URDF_TUTORIAL_MESSAGE_CHANGECONTROLLEDJOINTSRESPONSE_H
